version: '3.3'
services:
    mysql-net:
        container_name: mysql-net
        image: mysql:8
        restart: always
        environment: 
            MYSQL_DATABASE: 'company'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        volumes:
            - mysql-net-data-volume:/var/lib/mysql
volumes: 
    mysql-net-data-volume: null